---
- hosts: webservers
  remote_user: root
  tasks:
    - name: ensure all packages are installed
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python3.7
          - python3-pip
          - python3-virtualenv
          - python3-distutils
          - python3-gunicorn
          - gunicorn
      become: yes
    - name: clear existing app
      shell: rm -rf ./pylect
    - name: clone our web app
      git:
        repo: 'https://github.com/mdesenfants/pylect'
        dest: '~/pylect'
    - pip:
      requirements: ~/pylect/requirements.txt
    - name: run webservice on port 8080
      shell: python3 -m gunicorn atomic:app -p atomic.pid -b 0.0.0.0:8080 -D
      args:
        chdir: "~/pylect/"