---
- hosts: webservers
  remote_user: root
  tasks:
    - name: ensure all packages are installed
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python3-docker
          - docker
      become: yes
    - name: clear existing app
      file:
        path: ~/pylect
        state: absent
    - name: clone our web app
      git:
        repo: 'https://github.com/mdesenfants/pylect'
        dest: ~/pylect
    - name: build docker image
      shell: docker build -t pylect .
      args:
        chdir: ~/pylect
    - name: run docker container
      shell: docker run -d -p 8080:8080 pylect
      args:
        chdir: ~/pylect